routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'language'], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Auth::routes();
    Route::get('logout', 'Auth\LoginController@logout', function () {
        return abort(404);
    });

    Route::get('/home', 'ProdutoController@index')->name('home');
    Route::any('/buscar', 'BuscaController@index')->name('buscar');
    Route::resources([
        'produtos' => 'ProdutoController',
        'categorias' => 'CategoriaController'
    ]);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Pleno') }} - @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <script src="{{ asset('js/sweetalert/dist/sweetalert.min.js') }}"></script>
    <!-- Include this after the sweet alert js file - ->
    @include('sweet::alert')-->

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="btn btn-light nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre><img src="{{ asset('assets/img/flags/'. language()->country($locale = 'default') .'.svg') }}" alt="{{ language()->getName($code = 'default') }}" width="{{ config('language.flags.width') }}" /> {{ language()->getCode($name = 'default') }}</a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @foreach (language()->allowed() as $code => $name)
                                <a class="dropdown-item" href="{{ language()->back($code) }}">
                                    <img src="{{ asset('assets/img/flags/'. language()->country($code) .'.svg') }}" alt="{{ $name }}" width="{{ config('language.flags.width') }}" /> &nbsp; {{ $code }}
                                </a>
                                @endforeach
                            </div>

                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('produtos.index') }}">{{ __('Produtos') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('categorias.index') }}">{{ __('Categorias') }}</a>
                        </li>

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        <form method="get" action="{{ route('buscar') }}" class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" name="q" id="q" placeholder="{{ __('Buscar Produto') }}">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{{ __('Buscar') }}</button>
                        </form>

                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Cadastro') }}</a>
                        </li>
                        @endif
                        @else
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle btn btn-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <img src="{{ Gravatar::src(Auth::user()->email, 35) }}" class="rounded-circle">&nbsp; {{ Auth::user()->name }} &nbsp;<span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}">
                                    {{ __('Sair') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>