routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'language'], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Auth::routes();
    Route::get('logout', 'Auth\LoginController@logout', function () {
        return abort(404);
    });

    Route::get('/home', 'ProdutoController@index')->name('home');
    Route::any('/buscar', 'BuscaController@index')->name('buscar');
    Route::resources([
        'produtos' => 'ProdutoController',
        'categorias' => 'CategoriaController'
    ]);
});

app/Produto.php
<?php

namespace App;

use App\Categoria;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $fillable = ['nome', 'descricao', 'quantidade', 'preco', 'categoria_id'];

    public function categoria(){
        return $this->belongsTo(Categoria::class);
    }
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use App\Produto;
use App\Categoria;
use Alert;

use Illuminate\Http\Request;

class ProdutoController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $produtos = Produto::with('categoria')->paginate(10);
        return view('paginas/produtos/listar')->with('produtos', $produtos);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $categorias = Categoria::get();

        return view('paginas/produtos/CadastrarEditar')->with('categorias', $categorias);
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $produto = new Produto($request->all());
        $produto->save();

        Alert::success(__('O :produto foi criado',['produto' => $produto->nome]));
        return redirect()->route('produtos.index', $produto->id);
    }

    /**
    * Display the specified resource.
    *
    * @param  \App\Produto  $produto
    * @return \Illuminate\Http\Response
    */
    public function show(Produto $produto)
    {
        $produto = Produto::findOrFail($produto->id);
        return view('paginas/produtos/ver')->with('produto', $produto);
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Produto  $produto
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $produto = Produto::findOrFail($id);
        $categorias = Categoria::get();
        return view('paginas/produtos/CadastrarEditar')->with('produto', $produto)->with('categorias', $categorias);
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Produto  $produto
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Produto $produto)
    {
        $produto->update($request->all());
        Alert::success(__('O :produto foi atualizado',['produto' => $produto->nome]));
        return redirect()->route('produtos.index', $produto->id);
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Produto  $produto
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        $produto = Produto::findOrFail($id);
        $produto->delete();
        Alert::success(__('O :produto foi excluído',['produto' => $produto->nome]));
        return redirect()->route('produtos.index');
    }
}

resources/views/paginas/produtos/CadastrarEditar.blade.php
@extends('layouts.app')
@if(isset($produto))
@section('title', __('Editar Produto'))
@else
@section('title', __('Cadastrar Produto'))
@endif

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!--<div class="card text-center">-->
            <div class="card">
                <div class="card-header pt-6">
                    <h5 class="inline">
                        @if(isset($produto))
                        {{ __('Editar Produto') }}
                        @else
                        {{ __('Cadastrar Produto') }}
                        @endif
                    </h5>
                </div>

                <div class="card-body">
                    @if(isset($produto))
                    <form action="{{ route('produtos.update', $produto->id) }}" method="post">
                        <input type="hidden" name="_method" value="patch" />
                    @else
                    <form method="post" action="{{ route('produtos.store') }}">
                    @endif

                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="nome">{{ __('Nome') }}</label>
                            <input type="text" class="form-control" id="nome" name="nome" @if(isset($produto)) value="{{ $produto->nome }}"@endif placeholder="{{ __('Nome do Produto') }}">
                        </div>
                        <div class="form-group">
                            <label for="descricao">{{ __('Descrição') }}</label>
                            <input type="text" class="form-control" id="descricao" name="descricao" @if(isset($produto)) value="{{ $produto->descricao }}"@endif placeholder="{{ __('Descrição do Produto') }}">
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="quantidade">{{ __('Quantidade') }}</label>
                                <input type="text" class="form-control" id="quantidade" name="quantidade" @if(isset($produto)) value="{{ $produto->quantidade }}"@endif>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="categoria_id">{{ __('Categoria') }}</label>
                                <select id="categoria_id" name="categoria_id" class="form-control">
                                    @if(isset($produto))
                                    <option value="{{ $produto->categoria->id }}">{{ $produto->categoria->nome }}</option>
                                    @else
                                    <option selected>{{ __('Selecionar...') }}</option>
                                    @endif

                                    @foreach ($categorias as $categoria)
                                        <option value="{{ $categoria->id }}">{{ $categoria->nome }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="preco">{{ __('Preço') }}</label>
                                <input type="text" class="form-control" id="preco" name="preco" @if(isset($produto)) value="{{ $produto->preco }}"@endif>
                            </div>
                        </div>
                        <a href="{{url()->previous()}}" class="btn btn-danger">{{ __('Cancelar') }}</a>
                        <button type="submit" class="btn btn-primary">@if(isset($produto)) {{ __('Atualizar') }} @else  {{ __('Cadastrar') }} @endif</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/paginas/produtos/listar.blade.php
@extends('layouts.app')
@section('title', __('Listar Produtos'))

@section('content')
<!-- Include this after the sweet alert js file -->
@include('sweet::alert')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!--<div class="card text-center">-->
            <div class="card">

                <div class="card-header pt-6">
                    <h5 class="inline">{{ __('Produtos') }}
                        <a class="btn-sm btn btn-primary float-right" href="{{ route('produtos.create') }}">{{ __('Criar Produto') }}</a>
                    </h5>
                </div>

                @if ($produtos->isEmpty())
                <div class="card-body text-center">
                    <h5 class="card-title">Nenhum Produto foi encontrado</h5>
                    <p class="card-text">Você pode criar um novo Produto clicando no botão abaixo.</p>
                    <a href="{{ route('produtos.create') }}" class="btn btn-primary">{{ __('Criar Produto') }}</a>
                </div>

                @else

                <div class="card-body">

                    <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th class="th-sm">{{ __('Unidades') }}</th>
                                <th class="th-sm">{{ __('Nome') }}</th>
                                <th class="th-sm">{{ __('Descrição') }}</th>
                                <th class="th-sm">{{ __('Categoria') }}</th>
                                <th class="th-sm">{{ __('Preço') }}</th>
                                <th class="th-sm">{{ __('Ações') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($produtos as $produto)
                            <tr>
                                <td>{{ $produto->quantidade }}</td>
                                <td>{{ $produto->nome }}</td>
                                <td>{{ $produto->descricao }}</td>
                                <td>{{ $produto->categoria->nome }}</td>
                                <td>{{ $produto->preco }}</td>

                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ __('Ações') }}
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{ route('produtos.show',$produto->id) }}">{{ __('Ver') }}</a>
                                            <a class="dropdown-item" href="{{ route('produtos.edit',$produto->id) }}">{{ __('Editar') }}</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{{ route('produtos.destroy',$produto->id) }}" data-toggle="modal" data-target="#deletaProduto{{ $produto->id }}">{{ __('Excluir') }}</a>
                                        </div>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="deletaProduto{{ $produto->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="{{ $produto->nome }}">Excluíndo Produto {{ $produto->nome }}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    {{ __('Tem certeza que deseja Excluir o :item, está ação será irreversível.',['item'=>$produto->nome]) }}
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cancelar') }}</button>
                                                    <form action="{{ route('produtos.destroy', $produto->id) }}" method="post">
                                                        <input type="hidden" name="_method" value="delete" />
                                                        {!! csrf_field() !!}
                                                        <button type="submit" class="btn btn-danger">{{ __('Excluir') }}</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </table>

                        {{ $produtos->links() }}

                    </div>

                    @endif

                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/paginas/produtos/ver.blade.php
@extends('layouts.app')
@section('title', __('Ver Produto'))

@section('content')
<!-- Include this after the sweet alert js file -->
@include('sweet::alert')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!--<div class="card text-center">-->
            <div class="card">

                <div class="card-header pt-6">
                    <h5 class="inline">{{ __('Produtos') }}
                        <a class="btn-sm btn btn-primary float-right" href="{{ route('produtos.index') }}">{{ __('Voltar') }}</a>
                    </h5>
                </div>

                <div class="card-body">

                    <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th class="th-sm">{{ __('Unidades') }}</th>
                                <th class="th-sm">{{ __('Nome') }}</th>
                                <th class="th-sm">{{ __('Descrição') }}</th>
                                <th class="th-sm">{{ __('Categoria') }}</th>
                                <th class="th-sm">{{ __('Preço') }}</th>
                                <th class="th-sm">{{ __('Ações') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ $produto->quantidade }}</td>
                                <td>{{ $produto->nome }}</td>
                                <td>{{ $produto->descricao }}</td>
                                <td>{{ $produto->categoria->nome }}</td>
                                <td>{{ $produto->preco }}</td>

                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ __('Ações') }}
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{ route('produtos.edit',$produto->id) }}">{{ __('Editar') }}</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{{ route('produtos.destroy',$produto->id) }}" data-toggle="modal" data-target="#deletaProduto{{ $produto->id }}">{{ __('Excluir') }}</a>
                                        </div>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="deletaProduto{{ $produto->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="{{ $produto->nome }}">Excluíndo Produto {{ $produto->nome }}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    {{ __('Tem certeza que deseja Excluir o :item, está ação será irreversível.',['item'=>$produto->nome]) }}
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cancelar') }}</button>
                                                    <form action="{{ route('produtos.destroy', $produto->id) }}" method="post">
                                                        <input type="hidden" name="_method" value="delete" />
                                                        {!! csrf_field() !!}
                                                        <button type="submit" class="btn btn-danger">{{ __('Excluir') }}</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection